version: '3.8'

services:
  onnx-tester:
    build: .
    container_name: onnx-model-tester
    volumes:
      # Mount your models directory
      - ./models:/app/models
      # Mount outputs directory
      - ./outputs:/app/outputs
      # Mount your .env file
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    # Override default command for interactive use
    command: tail -f /dev/null
    # Uncomment below if you want to run a specific script
    # command: python your_script.py
    
  # Optional: Add a development service with mounted source code
  onnx-tester-dev:
    build: .
    container_name: onnx-model-tester-dev
    volumes:
      # Mount source code for development
      - .:/app
      # Mount models and outputs
      - ./models:/app/models
      - ./outputs:/app/outputs
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: tail -f /dev/null
    profiles:
      - dev 