name: Run ONNX Model in Swift (CLI)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  swift-onnx-inference:
    runs-on: macos-13

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install pod dependencies
        run: pod install

      - name: Build Swift CLI project
        run: |
          xcodebuild -workspace SwiftONNXRunner.xcworkspace \
                     -scheme SwiftONNXRunner \
                     -sdk macosx \
                     -destination 'platform=macOS' \
                     build

      - name: Run inference
        run: |
          ./build/Release/SwiftONNXRunner
